### ISSUE TITLE
Support of french installed language

### ISSUE THREAD

**Issue by Jean-Paul-M** [xr09/cron-last-sunday#4]
Hello,
If you update statement 33 : WEEK_DAY=${ARRAY[3]} by   WEEK_DAY=${ARRAY[3]:0:3} your shell works fine even in french (I think it works fine also in english).

In french, date +%a return 4 characters ("dim.","lun." , "mar."....)
Without the modification, run-if-today 1 "dim" or run-if-today 1 "dim." doesn't work.
Thanks a lot.

**Comment by xr09** [comment]
Bonjour @Jean-Paul-M!

You're right that seems to do the trick, had no idea date's output was like that in French.

```
~ 
❯ VAR=`LANG=french date +%a`
~ 
❯ echo ${VAR:0:3}
mer
```

 Would you like to do the honors and make a PR for this?

**Comment by Jean-Paul-M** [comment]
Hello,
No problem, but I don't know how to do that.
I suppose PR is program request ? Excuse me, I don't know Github at all.
If it's simpler for you, don't hesitate to create the PR.
Best regards

**Comment by xr09** [comment]
No worries I'll create myself, thinking of adding some testing capabilities with faketime to these different edge cases and other languages too.

A PR is a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests), it's how you collaborate on Github.

**Comment by PixelsIng** [comment]
Just change line 29 from :
ARRAY=( $(date "+%Y %m %d %a") )
to:
ARRAY=( $(LC_TIME=en_US.UTF-8 date "+%Y %m %d %a") )
to solve the issue, as ARRAY[3] will always contain english notation for week days

**Comment by Jean-Paul-M** [comment]
Hello,
Thanks to work on this issue !
But your new code doesn't work.
Here an extract of shell with set -e -x

+ ARRAY=($(LC_TIME=en_US.UTF-8 date "+%Y %m %d %a"))
++ LC_TIME=en_US.UTF-8
++ date '+%Y %m %d %a'
+ YEAR=2022
+ MONTH=08
+ TODAY=29
+ WEEK_DAY=lun.

I'm very sorry.
Best regards.
JP

**Comment by xr09** [comment]
Hello @Jean-Paul-M,

Sorry I haven't pushed any new code since you first reported it, this issue has passed under my radar, will get to it as soon as possible. Probably later today. :crossed_fingers:

**Comment by xr09** [comment]
There are two ways to solve this, one is by catering to the specifics of every language like you proposed on your first comment and the other is by forcing the date to use English like @PixelsIng proposed, I'm inclined to do the later since the first method would require to make fixes for every other locale with non-standard format.

Doing a quick test I see German and Dutch only print two characters for day of the week, that would be a problem.

```
LC_TIME=de_DE date +%a
Fr
LC_TIME=nl_NL date +%a
vr
```

**Comment by xr09** [comment]
Hey @Jean-Paul-M, it should work now with the fix proposed by @PixelsIng (thanks!)

By the way I believe this wasn't that big of a stopper since you can use the script without a seconds parameter (day of week) and let Cron worry about it.

This example will only run the 2nd Friday, and there's no need to specify `Fri` because Cron will only check it on Fridays (see the `5`).

```
0 5 * * 5 root run-if-today 2 && /opt/myscript.sh
```

Sorry for not specifying this long time ago, I wrote this script but nowadays rarely get to use it.
